import { ResumeData } from './resume-schema';
import { v4 as uuidv4 } from 'uuid';

export const createDefaultResume = (name: string = 'New Resume'): ResumeData => {
  const experienceId = uuidv4();
  const educationId = uuidv4();
  const skillsId = uuidv4();
  const projectsId = uuidv4();

  return {
    id: uuidv4(),
    name,
    picture: {
      url: '',
      size: 64,
      aspectRatio: 1,
      borderRadius: 0,
      opacity: 1,
    },
    basics: {
      name: 'John Doe',
      label: 'Full Stack Developer',
      email: 'john@example.com',
      phone: '+1 (555) 123-4567',
      url: 'https://johndoe.com',
      summary: 'Experienced full-stack developer with a passion for building modern web applications. Proficient in React, Node.js, and cloud technologies.',
      location: {
        address: '123 Main Street',
        postalCode: '12345',
        city: 'San Francisco',
        countryCode: 'US',
        region: 'California',
      },
      customFields: [],
    },
    summary: {
      id: 'summary',
      visible: true,
      name: 'Professional Summary',
      content: 'Experienced full-stack developer with a passion for building modern web applications. Proficient in React, Node.js, and cloud technologies. 5+ years of experience in software development.',
      columns: 1,
    },
    sections: {
      profiles: [
        {
          id: uuidv4(),
          network: 'LinkedIn',
          username: 'johndoe',
          url: 'https://linkedin.com/in/johndoe',
          icon: 'linkedin',
        },
        {
          id: uuidv4(),
          network: 'GitHub',
          username: 'johndoe',
          url: 'https://github.com/johndoe',
          icon: 'github',
        },
      ],
      experience: {
        id: experienceId,
        visible: true,
        name: 'Experience',
        items: [
          {
            id: uuidv4(),
            name: 'Tech Corp',
            position: 'Senior Full Stack Developer',
            startDate: '2021-01',
            endDate: undefined,
            isWorkingHere: true,
            location: 'San Francisco, CA',
            summary: 'Led development of key features for our main product, mentored junior developers, and improved system performance by 40%.',
            highlights: [
              'Led development of microservices architecture',
              'Improved application performance by 40%',
              'Mentored 3 junior developers',
              'Implemented CI/CD pipeline reducing deployment time by 60%',
            ],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'StartUp Labs',
            position: 'Full Stack Developer',
            startDate: '2019-06',
            endDate: '2020-12',
            isWorkingHere: false,
            location: 'Remote',
            summary: 'Built and maintained full-stack web applications using React and Node.js.',
            highlights: [
              'Developed REST APIs serving 100k+ daily users',
              'Optimized database queries reducing response time by 30%',
              'Implemented real-time notifications using WebSockets',
            ],
            visible: true,
          },
        ],
      },
      education: {
        id: educationId,
        visible: true,
        name: 'Education',
        items: [
          {
            id: uuidv4(),
            institution: 'State University',
            studyType: 'Bachelor of Science',
            area: 'Computer Science',
            startDate: '2015-09',
            endDate: '2019-05',
            score: '3.8',
            summary: 'Focused on web development and software architecture',
            visible: true,
          },
        ],
      },
      skills: {
        id: skillsId,
        visible: true,
        name: 'Skills',
        items: [
          {
            id: uuidv4(),
            name: 'JavaScript/TypeScript',
            level: 'Expert',
            keywords: ['ES6+', 'Async/Await', 'Promises'],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'React',
            level: 'Expert',
            keywords: ['Hooks', 'Context API', 'Performance Optimization'],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'Node.js',
            level: 'Expert',
            keywords: ['Express', 'REST APIs', 'Database Design'],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'Next.js',
            level: 'Advanced',
            keywords: ['SSR', 'API Routes', 'Deployment'],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'Database Design',
            level: 'Advanced',
            keywords: ['PostgreSQL', 'MongoDB', 'Redis'],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'Cloud Platforms',
            level: 'Advanced',
            keywords: ['AWS', 'GCP', 'Docker', 'Kubernetes'],
            visible: true,
          },
        ],
      },
      projects: {
        id: projectsId,
        visible: true,
        name: 'Projects',
        items: [
          {
            id: uuidv4(),
            name: 'Task Management Platform',
            description: 'A collaborative task management application built with React and Node.js',
            keywords: ['React', 'Node.js', 'PostgreSQL', 'Real-time'],
            startDate: '2022-03',
            endDate: '2022-09',
            url: 'https://taskapp.example.com',
            roles: ['Lead Developer'],
            entity: 'Personal Project',
            type: 'Application',
            highlights: [
              'Implemented real-time collaboration using WebSockets',
              'Designed PostgreSQL schema for optimal query performance',
              'Achieved 95% test coverage with Jest and React Testing Library',
            ],
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'Data Visualization Dashboard',
            description: 'Analytics dashboard for visualizing large datasets',
            keywords: ['React', 'D3.js', 'Node.js'],
            startDate: '2021-09',
            endDate: '2022-02',
            url: 'https://dashboard.example.com',
            roles: ['Full Stack Developer'],
            entity: 'Tech Corp',
            type: 'Application',
            highlights: [
              'Built interactive charts handling 100k+ data points',
              'Implemented server-side rendering for improved performance',
              'Created reusable component library',
            ],
            visible: true,
          },
        ],
      },
      languages: {
        id: uuidv4(),
        visible: true,
        name: 'Languages',
        items: [
          {
            id: uuidv4(),
            name: 'English',
            description: 'Native Speaker',
            visible: true,
          },
          {
            id: uuidv4(),
            name: 'Spanish',
            description: 'Conversational',
            visible: true,
          },
        ],
      },
      interests: {
        id: uuidv4(),
        visible: true,
        name: 'Interests',
        items: [
          {
            id: uuidv4(),
            name: 'Open Source Development',
            keywords: ['Contributing', 'Maintaining Libraries'],
          },
          {
            id: uuidv4(),
            name: 'Web Performance',
            keywords: ['Optimization', 'Core Web Vitals'],
          },
          {
            id: uuidv4(),
            name: 'Teaching & Mentoring',
            keywords: ['Junior Developers', 'Workshops'],
          },
        ],
      },
      certifications: {
        id: uuidv4(),
        visible: true,
        name: 'Certifications',
        items: [
          {
            id: uuidv4(),
            name: 'AWS Certified Solutions Architect',
            issuer: 'Amazon Web Services',
            date: '2023-06',
            summary: '',
            url: 'https://aws.example.com',
          },
          {
            id: uuidv4(),
            name: 'Kubernetes Application Developer',
            issuer: 'Linux Foundation',
            date: '2023-03',
            summary: '',
            url: 'https://linux.example.com',
          },
        ],
      },
    },
    customSections: [],
    metadata: {
      template: 'modern',
      layout: {
        template: 'modern',
        pageSize: 'A4',
        sidebarWidth: 35,
        hiddenSections: [],
        itemsPerPage: 999,
      },
      design: {
        primaryColor: '#2563eb',
        background: '#ffffff',
        accent: '#0066cc',
        text: '#000000',
        border: '#e0e0e0',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        fontSize: 10,
        lineHeight: 1.5,
      },
      page: {
        width: 210,
        height: 297,
        margin: 20,
      },
      css: '',
      notes: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  };
};

export const createEmptyResume = (name: string = 'New Resume'): ResumeData => {
  return {
    id: uuidv4(),
    name,
    picture: {
      url: '',
      size: 64,
      aspectRatio: 1,
      borderRadius: 0,
      opacity: 1,
    },
    basics: {
      name: '',
      label: '',
      email: '',
      phone: '',
      url: '',
      summary: '',
      location: {
        address: '',
        postalCode: '',
        city: '',
        countryCode: '',
        region: '',
      },
      customFields: [],
    },
    summary: {
      id: 'summary',
      visible: true,
      name: 'Professional Summary',
      content: '',
      columns: 1,
    },
    sections: {
      profiles: [],
      experience: {
        id: uuidv4(),
        visible: true,
        name: 'Experience',
        items: [],
      },
      education: {
        id: uuidv4(),
        visible: true,
        name: 'Education',
        items: [],
      },
      skills: {
        id: uuidv4(),
        visible: true,
        name: 'Skills',
        items: [],
      },
      projects: {
        id: uuidv4(),
        visible: true,
        name: 'Projects',
        items: [],
      },
      languages: {
        id: uuidv4(),
        visible: true,
        name: 'Languages',
        items: [],
      },
      interests: {
        id: uuidv4(),
        visible: true,
        name: 'Interests',
        items: [],
      },
      certifications: {
        id: uuidv4(),
        visible: true,
        name: 'Certifications',
        items: [],
      },
    },
    customSections: [],
    metadata: {
      template: 'modern',
      layout: {
        template: 'modern',
        pageSize: 'A4',
        sidebarWidth: 35,
        hiddenSections: [],
        itemsPerPage: 999,
      },
      design: {
        primaryColor: '#2563eb',
        background: '#ffffff',
        accent: '#0066cc',
        text: '#000000',
        border: '#e0e0e0',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        fontSize: 10,
        lineHeight: 1.5,
      },
      page: {
        width: 210,
        height: 297,
        margin: 20,
      },
      css: '',
      notes: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  };
};
